ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_locale TEXT NOT NULL DEFAULT 'en';
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_skin TEXT NOT NULL DEFAULT 'taras';
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_theme TEXT NOT NULL DEFAULT 'dark';
